<?php

namespace Modules\AppDomoprime\Services;

use Illuminate\Support\Facades\Log;
use RuntimeException;

class PdftkService
{
    protected string $binary;

    public function __construct()
    {
        $this->binary = config('appdomoprime.pdftk_binary', 'C:\\Program Files (x86)\\PDFtk Server\\bin\\pdftk.exe');
    }

    /**
     * Fill a PDF form with data using XFDF and flatten the result.
     */
    public function fillForm(string $templatePath, array $data, string $outputPath): void
    {
        $xfdfPath = $outputPath . '.xfdf';
        $this->writeXfdf($xfdfPath, $data);

        $cmd = sprintf(
            '"%s" "%s" fill_form "%s" output "%s" flatten',
            $this->binary,
            $templatePath,
            $xfdfPath,
            $outputPath
        );

        $this->run($cmd);

        @unlink($xfdfPath);
    }

    /**
     * Burst a PDF into individual pages.
     *
     * @return int Number of pages generated
     */
    public function burst(string $pdfPath, string $outputDir): int
    {
        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0755, true);
        }

        $cmd = sprintf(
            '"%s" "%s" burst output "%s"',
            $this->binary,
            $pdfPath,
            $outputDir . DIRECTORY_SEPARATOR . '%d.pdf'
        );

        $this->run($cmd);

        // Count generated page files
        $count = 0;
        while (file_exists($outputDir . DIRECTORY_SEPARATOR . ($count + 1) . '.pdf')) {
            $count++;
        }

        // Remove doc_data.txt generated by burst
        $docData = $outputDir . DIRECTORY_SEPARATOR . 'doc_data.txt';
        if (file_exists($docData)) {
            @unlink($docData);
        }

        return $count;
    }

    /**
     * Stamp a base PDF with an overlay PDF (background/watermark).
     */
    public function stamp(string $basePdf, string $stampPdf, string $outputPath): void
    {
        $cmd = sprintf(
            '"%s" "%s" stamp "%s" output "%s"',
            $this->binary,
            $basePdf,
            $stampPdf,
            $outputPath
        );

        $this->run($cmd);
    }

    /**
     * Merge multiple PDFs into one using cat.
     */
    public function merge(array $pdfPaths, string $outputPath): void
    {
        if (count($pdfPaths) === 0) {
            throw new RuntimeException('No PDF files to merge.');
        }

        if (count($pdfPaths) === 1) {
            copy($pdfPaths[0], $outputPath);
            return;
        }

        $files = implode('" "', $pdfPaths);

        $cmd = sprintf(
            '"%s" "%s" cat output "%s"',
            $this->binary,
            $files,
            $outputPath
        );

        $this->run($cmd);
    }

    /**
     * Generate XFDF XML content for form filling.
     */
    protected function writeXfdf(string $path, array $data): void
    {
        $fields = '';
        foreach ($data as $name => $value) {
            $escapedName = htmlspecialchars((string) $name, ENT_XML1, 'UTF-8');
            $escapedValue = htmlspecialchars((string) $value, ENT_XML1, 'UTF-8');
            $fields .= '<field name="' . $escapedName . '"><value>' . $escapedValue . '</value></field>' . "\n";
        }

        $xfdf = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><fields>' . "\n"
            . $fields
            . '</fields></xfdf>';

        file_put_contents($path, $xfdf);
    }

    /**
     * Execute a shell command and handle errors.
     */
    protected function run(string $cmd): void
    {
        Log::debug('[PdftkService] Running: ' . $cmd);

        $output = [];
        $returnCode = 0;
        exec($cmd . ' 2>&1', $output, $returnCode);

        if ($returnCode !== 0) {
            $outputStr = implode("\n", $output);
            Log::error('[PdftkService] Command failed (code ' . $returnCode . '): ' . $outputStr);
            throw new RuntimeException('PDFtk command failed (code ' . $returnCode . '): ' . $outputStr);
        }
    }
}
